### Preprocessing the data
##### for sci-kit learn to understand it as it can't understand our language

In [1]:
import pandas as pd

In [2]:
data = {
    "Color": ["Red","Blue","Green","Blue","Red","Green","Blue","Red"],
    "Size": ["Small","Medium","Large","Small","Medium","Large","Small","Large"],
    "City": ["Delhi","Mumbai","Bangalore","Delhi","Chennai","Mumbai","Bangalore","Chennai"],
    "Price": [120,150,80,200,130,95,170,220],
    "Purchased": ["Yes","No","Yes","Yes","No","No","Yes","Yes"]
}

df = pd.DataFrame(data)
df

   Color    Size       City  Price Purchased
0    Red   Small      Delhi    120       Yes
1   Blue  Medium     Mumbai    150        No
2  Green   Large  Bangalore     80       Yes
3   Blue   Small      Delhi    200       Yes
4    Red  Medium    Chennai    130        No
5  Green   Large     Mumbai     95        No
6   Blue   Small  Bangalore    170       Yes
7    Red   Large    Chennai    220       Yes

## Data to meaningful numbers for learning | Preprocessing

### 1. Label Encoding 
- Yes -> 1
- No -> 0

- R -> 0
- G -> 1
- B -> 2

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [4]:
y = df['Purchased']
# y = df['Color']
label_enc = LabelEncoder()
y_enc = label_enc.fit_transform(y)
y_enc

# Inverse transform 
# y_dec = label_enc.inverse_transform(y_enc)
# y_dec

array([1, 0, 1, 1, 0, 0, 1, 1])

### OneHot Encoding
- a table of yes and no with 1 for yes and 0 for no
- y n
- 1 0
- 1 0
- 0 1

In [5]:
one_hot_enc = OneHotEncoder()
# takes 2D array
# y_enc = pd.DataFrame(one_hot_enc.fit_transform(df[["Purchased"]]).toarray())
y_enc = pd.DataFrame(one_hot_enc.fit_transform(df[["Price"]]).toarray())
# y_enc = pd.DataFrame(one_hot_enc.fit_transform(df[["Color"]]).toarray())
y_enc
# print(y_enc.to_string(index=False))

# y_dec = one_hot_enc.inverse_transform(y_enc)
# y_dec

     0    1    2    3    4    5    6    7
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
6  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

### MinMax Scaler

#### Formula: X' = (X - Xmin) / (Xmax - Xmin)

```
X -> 1 2 3 4 5

Xmin = 1, Xmax = 5

Take first -> 1
X0 = (1 - 1) / (5 - 1) = 0
X1 = (2 - 1) / (5 - 1) = 1/4 = 0.25
X2 = (3 - 1) / (5 - 1) = 2/4 = 0.50
X3 = (4 - 1) / (5 - 1) = 3/4 = 0.75
X4 = (5 - 1) / (5 - 1) = 4/4 = 1.00
```

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
import numpy as np

df = pd.DataFrame({
    'C1': [1,2,3,4,5],
    'C2': [6,7,8,12,14]
}, index=['a', 'b', 'c', 'd', 'e'])

df

   C1  C2
a   1   6
b   2   7
c   3   8
d   4  12
e   5  14

In [8]:
m = MinMaxScaler()
m.fit_transform(df)

array([[0.   , 0.   ],
       [0.25 , 0.125],
       [0.5  , 0.25 ],
       [0.75 , 0.75 ],
       [1.   , 1.   ]])

### Binarizer Preprocessing - to binarize data

In [9]:
from sklearn.preprocessing import Binarizer

In [11]:
b = Binarizer(threshold=5) 
# greater than 5 will be marked as 1 and less than or equal 5 will be marked as 0
# default threshold is 0

# random data can't be handled properly .. so we binarize it first
arr = np.array([[13, 10, 21], [21, 2, 1], [3, 5, 5]]) # 2D array

binary1 = b.transform(arr)
# binary1 = b.fit_transform(arr)
binary1

# used in Bernoulli Naive Bayes

array([[1, 1, 1],
       [1, 0, 0],
       [0, 0, 0]])